- hosts: app_servers
  become: true
  tasks:
    - name: Gather all facts
      setup:

    - name: Debug OS and Package Manager
      debug:
        msg:
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "OS Family: {{ ansible_facts['os_family'] }}"
          - "Package Manager: {{ ansible_facts['pkg_mgr'] }}"

    - name: Install Apache using yum
      command: yum install -y httpd
      when: ansible_facts['distribution'] == 'Amazon'

    - name: Start Apache service
      command: systemctl start httpd
      when: ansible_facts['distribution'] == 'Amazon'

    - name: Enable Apache service
      command: systemctl enable httpd
      when: ansible_facts['distribution'] == 'Amazon'
